# Generated by Django 2.1 on 2019-05-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
