# Generated by Django 2.1 on 2019-05-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190506_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='parent',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddIndex(
            model_name='productname',
            index=models.Index(fields=['level'], name='level_idx'),
        ),
        migrations.AddIndex(
            model_name='productname',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
