# Generated by Django 2.1 on 2019-05-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_productnamespecs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnamespecs',
            name='specs',
        ),
        migrations.AddField(
            model_name='productnamespecs',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productnamespecs',
            name='volumn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productnamespecs',
            name='weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productnamespecs',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
