# Generated by Django 2.1 on 2019-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190507_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnamespecs',
            name='length',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
