# Generated by Django 2.1 on 2019-05-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_productnamespecs_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnamespecs',
            name='remark',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
