# Generated by Django 2.1 on 2019-05-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_enterprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('child', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '公司名称分析',
                'verbose_name_plural': '公司名称分析',
            },
        ),
    ]
