# Generated by Django 2.1 on 2019-05-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_enterprisesplit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisesplit',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesplit',
            name='child',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisesplit',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
