# Generated by Django 2.1 on 2019-05-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20190511_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisesplit',
            name='province',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['level'], name='enterprise_level_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprise',
            index=models.Index(fields=['name'], name='enterprise_name_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisesplit',
            index=models.Index(fields=['level'], name='EnterpriseSplit_level_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisesplit',
            index=models.Index(fields=['name'], name='EnterpriseSplit_name_idx'),
        ),
    ]
