# Generated by Django 2.1 on 2019-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20190513_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisesplit',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
